# Generated by Django 3.2.16 on 2022-11-17 16:01

from django.db import migrations, models
import django.db.models.deletion
import forex.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReportStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('comment', models.TextField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportHistoryPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_high', models.FloatField()),
                ('prediction_low', models.FloatField()),
                ('target_datetime', models.DateTimeField()),
                ('predicted_hit_high', models.DateTimeField(null=True)),
                ('predicted_hit_low', models.DateTimeField(null=True)),
                ('current_date_time', models.DateTimeField(auto_now_add=True)),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.currency')),
                ('interval_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.interval')),
                ('report_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.reportstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField(null=True)),
                ('to_date', models.DateTimeField(null=True)),
                ('percentage', models.FloatField(default=0.0)),
                ('report_date_time', models.DateTimeField(auto_now_add=True)),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.currency')),
                ('interval_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.interval')),
                ('report_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.reportstatus')),
            ],
        ),
        migrations.CreateModel(
            name='ForexModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_high', models.FileField(upload_to=forex.models.uploada_path_handler)),
                ('model_low', models.FileField(upload_to=forex.models.uploada_path_handler)),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.currency')),
                ('interval_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.interval')),
            ],
        ),
    ]
